### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by spuder** [chadharrington/all_spark_cube#1]
I am able to execute python tetris.py while ssh'ed into the cube directly. 

When I try and execute tetris.py with the client running on my Mac, I receive the following error. 

```
sowen@pv-sowen-nb:~/Code/all_spark_cube/software/clients/python_client/src$ python tetris.py 
Traceback (most recent call last):
  File "tetris.py", line 5, in <module>
    from all_spark_cube_client import CubeClient
  File "/Users/sowen/Code/all_spark_cube/software/clients/python_client/src/all_spark_cube_client/__init__.py", line 8, in <module>
    from cube_interface import CubeInterface
ImportError: No module named cube_interface
```

I've tried setting my python path to include~/Code/all_spark_cube/software/clients/python_client/src

Do you know why python is unable to find the cube_interface module?

**Comment by chadharrington** [comment]
Did you use the client tarball that I sent via email or are you running
from the git checkout?

Chad Harrington
chad.harrington@gmail.com

**Comment by spuder** [comment]
I did a git clone

**Comment by chadharrington** [comment]
You'll need to do a build before running the client. The build uses Thrift
to generate the client library. You'll need to install thrift (hard-ish) or
use the prebuilt python client tarball that I sent yesterday. I have
attached it again here. I should add a releases directory to the git repo
that has the prebuilt libraries.

Chad Harrington
chad.harrington@gmail.com

**Comment by spuder** [comment]
Ok thanks!
