### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by petreg** [chadharrington/all_spark_cube#4]
First, sorry, my English is very bad and I'm using Google translator.
I would like to know how to assemble the circuit LEDs. I can not understand how to put together the 4096 leds with all RGBs connector. And I want to take a doubt, the data in this Github project, he used to program the de0-nano also? Yes I know I just need to ask you build a cube allspak for me, but if you can help me I would create a allsaprk for me. 

> Thank you.

**Comment by chadharrington** [comment]
Hi @petreg,
Building a large cube like we did might not be a good idea.  The 16x16x16 RGB cube cost around $10K to build and took a man-year or more. We also don't have time to document the build process, as it is very complicated. Here are some other LED cube projects with very good documentation:
- 4x4x4 RGB cube: http://www.instructables.com/id/4x4x4-RGB-LED-Cube/?ALLSTEPS
- 8x8x8 monochrome cube: http://www.instructables.com/id/Led-Cube-8x8x8/?ALLSTEPS
- 8x8x8 RGB cube: http://www.instructables.com/id/8X8X8-RGB-LED-Cube/?ALLSTEPS
